INCLUDEPATH += \
	/home/nick/UnrealEngine/Engine/Source \
	Plugins/JSONQuery/Source \
	Plugins/JSONQuery/Source/JSONQuery/Classes \
	Plugins/JSONQuery/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/JSONQuery \
	Plugins/JSONQuery/Source/JSONQuery \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Core/Public \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Core/Public/Internationalization \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Core/Public/Async \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Core/Public/Concurrency \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Core/Public/Containers \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Core/Public/Delegates \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Core/Public/GenericPlatform \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Core/Public/HAL \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Core/Public/Logging \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Core/Public/Math \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Core/Public/Misc \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Core/Public/Modules \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Core/Public/Modules/Boilerplate \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Core/Public/ProfilingDebugging \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Core/Public/Serialization \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Core/Public/Serialization/Csv \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Core/Public/Stats \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Core/Public/Templates \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Core/Public/UObject \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Core/Public/Linux \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Core \
	/home/nick/UnrealEngine/Engine/Source/Runtime/CoreUObject/Public \
	/home/nick/UnrealEngine/Engine/Source/Runtime/CoreUObject/Public/Blueprint \
	/home/nick/UnrealEngine/Engine/Source/Runtime/CoreUObject/Public/Internationalization \
	/home/nick/UnrealEngine/Engine/Source/Runtime/CoreUObject/Public/Misc \
	/home/nick/UnrealEngine/Engine/Source/Runtime/CoreUObject/Public/Serialization \
	/home/nick/UnrealEngine/Engine/Source/Runtime/CoreUObject/Public/Templates \
	/home/nick/UnrealEngine/Engine/Source/Runtime/CoreUObject/Public/UObject \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/CoreUObject \
	/home/nick/UnrealEngine/Engine/Source/Runtime/CoreUObject \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Engine/Classes \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Engine/Public \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Engine/Public/AI \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Engine/Public/AI/Navigation \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Engine/Public/Animation \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Engine/Public/Curves \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Engine/Public/EdGraph \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Engine/Public/Internationalization \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Engine/Public/Net \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Engine/Public/PacketHandlers \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Engine/Public/Performance \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Engine/Public/Physics \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Engine/Public/ProfilingDebugging \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Engine/Public/Rendering \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Engine/Public/Slate \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Engine/Public/Tests \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Engine/Public/VisualLogger \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Engine \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Engine \
	/home/nick/UnrealEngine/Engine/Source/Runtime/ApplicationCore/Public \
	/home/nick/UnrealEngine/Engine/Source/Runtime/ApplicationCore/Public/GenericPlatform \
	/home/nick/UnrealEngine/Engine/Source/Runtime/ApplicationCore/Public/HAL \
	/home/nick/UnrealEngine/Engine/Source/Runtime/ApplicationCore/Public/Linux \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/ApplicationCore \
	/home/nick/UnrealEngine/Engine/Source/Runtime/ApplicationCore \
	/home/nick/UnrealEngine/Engine/Source/Runtime/RHI/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/RHI \
	/home/nick/UnrealEngine/Engine/Source/Runtime/RHI \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Json/Public \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Json/Public/Dom \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Json/Public/Policies \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Json/Public/Serialization \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Json \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Json \
	/home/nick/UnrealEngine/Engine/Source/Runtime/SlateCore/Public \
	/home/nick/UnrealEngine/Engine/Source/Runtime/SlateCore/Public/Animation \
	/home/nick/UnrealEngine/Engine/Source/Runtime/SlateCore/Public/Application \
	/home/nick/UnrealEngine/Engine/Source/Runtime/SlateCore/Public/Brushes \
	/home/nick/UnrealEngine/Engine/Source/Runtime/SlateCore/Public/Fonts \
	/home/nick/UnrealEngine/Engine/Source/Runtime/SlateCore/Public/Input \
	/home/nick/UnrealEngine/Engine/Source/Runtime/SlateCore/Public/Layout \
	/home/nick/UnrealEngine/Engine/Source/Runtime/SlateCore/Public/Logging \
	/home/nick/UnrealEngine/Engine/Source/Runtime/SlateCore/Public/Rendering \
	/home/nick/UnrealEngine/Engine/Source/Runtime/SlateCore/Public/Sound \
	/home/nick/UnrealEngine/Engine/Source/Runtime/SlateCore/Public/Stats \
	/home/nick/UnrealEngine/Engine/Source/Runtime/SlateCore/Public/Styling \
	/home/nick/UnrealEngine/Engine/Source/Runtime/SlateCore/Public/Textures \
	/home/nick/UnrealEngine/Engine/Source/Runtime/SlateCore/Public/Types \
	/home/nick/UnrealEngine/Engine/Source/Runtime/SlateCore/Public/Widgets \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/SlateCore \
	/home/nick/UnrealEngine/Engine/Source/Runtime/SlateCore \
	/home/nick/UnrealEngine/Engine/Source/Runtime/InputCore/Classes \
	/home/nick/UnrealEngine/Engine/Source/Runtime/InputCore/Public \
	/home/nick/UnrealEngine/Engine/Source/Runtime/InputCore/Public/GenericPlatform \
	/home/nick/UnrealEngine/Engine/Source/Runtime/InputCore/Public/HAL \
	/home/nick/UnrealEngine/Engine/Source/Runtime/InputCore/Public/Linux \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/InputCore \
	/home/nick/UnrealEngine/Engine/Source/Runtime/InputCore \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Slate/Public \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Slate/Public/Framework \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Slate/Public/Framework/Application \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Slate/Public/Framework/Commands \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Slate/Public/Framework/Docking \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Slate/Public/Framework/Layout \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Slate/Public/Framework/MetaData \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Slate/Public/Framework/MultiBox \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Slate/Public/Framework/Notifications \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Slate/Public/Framework/Styling \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Slate/Public/Framework/Text \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Slate/Public/Framework/Views \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Slate/Public/Widgets \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Slate/Public/Widgets/Colors \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Slate/Public/Widgets/Docking \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Slate/Public/Widgets/Images \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Slate/Public/Widgets/Input \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Slate/Public/Widgets/LayerManager \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Slate/Public/Widgets/Layout \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Slate/Public/Widgets/Navigation \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Slate/Public/Widgets/Notifications \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Slate/Public/Widgets/Text \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Slate/Public/Widgets/Views \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Slate \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Slate \
	/home/nick/UnrealEngine/Engine/Source/Runtime/ImageWrapper/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/ImageWrapper \
	/home/nick/UnrealEngine/Engine/Source/Runtime/ImageWrapper \
	/home/nick/UnrealEngine/Engine/Source/Runtime/MessagingCommon/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/MessagingCommon \
	/home/nick/UnrealEngine/Engine/Source/Runtime/MessagingCommon \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Messaging/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Messaging \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Messaging \
	/home/nick/UnrealEngine/Engine/Source/Runtime/RenderCore/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/RenderCore \
	/home/nick/UnrealEngine/Engine/Source/Runtime/RenderCore \
	/home/nick/UnrealEngine/Engine/Source/Runtime/ShaderCore/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/ShaderCore \
	/home/nick/UnrealEngine/Engine/Source/Runtime/ShaderCore \
	/home/nick/UnrealEngine/Engine/Source/Runtime/UtilityShaders/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/UtilityShaders \
	/home/nick/UnrealEngine/Engine/Source/Runtime/UtilityShaders \
	/home/nick/UnrealEngine/Engine/Source/Runtime/AssetRegistry/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/AssetRegistry \
	/home/nick/UnrealEngine/Engine/Source/Runtime/AssetRegistry \
	/home/nick/UnrealEngine/Engine/Source/Runtime/EngineMessages/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/EngineMessages \
	/home/nick/UnrealEngine/Engine/Source/Runtime/EngineMessages \
	/home/nick/UnrealEngine/Engine/Source/Runtime/EngineSettings/Classes \
	/home/nick/UnrealEngine/Engine/Source/Runtime/EngineSettings/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/EngineSettings \
	/home/nick/UnrealEngine/Engine/Source/Runtime/EngineSettings \
	/home/nick/UnrealEngine/Engine/Source/Runtime/SynthBenchmark/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/SynthBenchmark \
	/home/nick/UnrealEngine/Engine/Source/Runtime/SynthBenchmark \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Renderer/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Renderer \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Renderer \
	/home/nick/UnrealEngine/Engine/Source/Runtime/GameplayTags/Classes \
	/home/nick/UnrealEngine/Engine/Source/Runtime/GameplayTags/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/GameplayTags \
	/home/nick/UnrealEngine/Engine/Source/Runtime/GameplayTags \
	/home/nick/UnrealEngine/Engine/Source/Runtime/AIModule/Public \
	/home/nick/UnrealEngine/Engine/Source/Runtime/AIModule/Classes \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/AIModule \
	/home/nick/UnrealEngine/Engine/Source/Runtime/AIModule \
	/home/nick/UnrealEngine/Engine/Source/Runtime/GameplayTasks/Classes \
	/home/nick/UnrealEngine/Engine/Source/Runtime/GameplayTasks/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/GameplayTasks \
	/home/nick/UnrealEngine/Engine/Source/Runtime/GameplayTasks \
	/home/nick/UnrealEngine/Engine/Source/Runtime/DatabaseSupport/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/DatabaseSupport \
	/home/nick/UnrealEngine/Engine/Source/Runtime/DatabaseSupport \
	/home/nick/UnrealEngine/Engine/Source/Runtime/PacketHandlers/PacketHandler/Classes \
	/home/nick/UnrealEngine/Engine/Source/Runtime/PacketHandlers/PacketHandler/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/PacketHandler \
	/home/nick/UnrealEngine/Engine/Source/Runtime/PacketHandlers/PacketHandler \
	/home/nick/UnrealEngine/Engine/Source/Runtime/PacketHandlers/ReliabilityHandlerComponent/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/ReliabilityHandlerComponent \
	/home/nick/UnrealEngine/Engine/Source/Runtime/PacketHandlers/ReliabilityHandlerComponent \
	/home/nick/UnrealEngine/Engine/Source/Runtime/HardwareSurvey/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/HardwareSurvey \
	/home/nick/UnrealEngine/Engine/Source/Runtime/HardwareSurvey \
	/home/nick/UnrealEngine/Engine/Source/Programs/UnrealLightmass/Public \
	/home/nick/UnrealEngine/Engine/Source/Editor/UnrealEd/Classes \
	/home/nick/UnrealEngine/Engine/Source/Editor/UnrealEd/Public \
	/home/nick/UnrealEngine/Engine/Source/Editor/UnrealEd/Public/AutoReimport \
	/home/nick/UnrealEngine/Engine/Source/Editor/UnrealEd/Public/Commandlets \
	/home/nick/UnrealEngine/Engine/Source/Editor/UnrealEd/Public/Dialogs \
	/home/nick/UnrealEngine/Engine/Source/Editor/UnrealEd/Public/DragAndDrop \
	/home/nick/UnrealEngine/Engine/Source/Editor/UnrealEd/Public/Features \
	/home/nick/UnrealEngine/Engine/Source/Editor/UnrealEd/Public/Kismet2 \
	/home/nick/UnrealEngine/Engine/Source/Editor/UnrealEd/Public/Layers \
	/home/nick/UnrealEngine/Engine/Source/Editor/UnrealEd/Public/Settings \
	/home/nick/UnrealEngine/Engine/Source/Editor/UnrealEd/Public/Tests \
	/home/nick/UnrealEngine/Engine/Source/Editor/UnrealEd/Public/Toolkits \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/UnrealEd \
	/home/nick/UnrealEngine/Engine/Source/Editor/UnrealEd \
	/home/nick/UnrealEngine/Engine/Source/Editor/BspMode/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/BspMode \
	/home/nick/UnrealEngine/Engine/Source/Editor/BspMode \
	/home/nick/UnrealEngine/Engine/Source/Developer/DirectoryWatcher/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/DirectoryWatcher \
	/home/nick/UnrealEngine/Engine/Source/Developer/DirectoryWatcher \
	/home/nick/UnrealEngine/Engine/Source/Editor/Documentation/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Documentation \
	/home/nick/UnrealEngine/Engine/Source/Editor/Documentation \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Projects/Public \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Projects/Public/Interfaces \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Projects \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Projects \
	/home/nick/UnrealEngine/Engine/Source/Runtime/SandboxFile/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/SandboxFile \
	/home/nick/UnrealEngine/Engine/Source/Runtime/SandboxFile \
	/home/nick/UnrealEngine/Engine/Source/Editor/EditorStyle/Public \
	/home/nick/UnrealEngine/Engine/Source/Editor/EditorStyle/Public/Classes \
	/home/nick/UnrealEngine/Engine/Source/Editor/EditorStyle/Public/Interfaces \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/EditorStyle \
	/home/nick/UnrealEngine/Engine/Source/Editor/EditorStyle \
	/home/nick/UnrealEngine/Engine/Source/Developer/SourceControl/Public \
	/home/nick/UnrealEngine/Engine/Source/Developer/SourceControl/Public/Tests \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/SourceControl \
	/home/nick/UnrealEngine/Engine/Source/Developer/SourceControl \
	/home/nick/UnrealEngine/Engine/Source/Editor/UnrealEdMessages/Classes \
	/home/nick/UnrealEngine/Engine/Source/Editor/UnrealEdMessages/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/UnrealEdMessages \
	/home/nick/UnrealEngine/Engine/Source/Editor/UnrealEdMessages \
	/home/nick/UnrealEngine/Engine/Source/Developer/GameplayDebugger/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/GameplayDebugger \
	/home/nick/UnrealEngine/Engine/Source/Developer/GameplayDebugger \
	/home/nick/UnrealEngine/Engine/Source/Editor/BlueprintGraph/Classes \
	/home/nick/UnrealEngine/Engine/Source/Editor/BlueprintGraph/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/BlueprintGraph \
	/home/nick/UnrealEngine/Engine/Source/Editor/BlueprintGraph \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Online/HTTP/Public \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Online/HTTP/Public/GenericPlatform \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Online/HTTP/Public/Interfaces \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Online/HTTP/Public/Linux \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/HTTP \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Online/HTTP \
	/home/nick/UnrealEngine/Engine/Source/Runtime/UnrealAudio/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/UnrealAudio \
	/home/nick/UnrealEngine/Engine/Source/Runtime/UnrealAudio \
	/home/nick/UnrealEngine/Engine/Source/Developer/FunctionalTesting/Classes \
	/home/nick/UnrealEngine/Engine/Source/Developer/FunctionalTesting/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/FunctionalTesting \
	/home/nick/UnrealEngine/Engine/Source/Developer/FunctionalTesting \
	/home/nick/UnrealEngine/Engine/Source/Developer/AutomationController/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/AutomationController \
	/home/nick/UnrealEngine/Engine/Source/Developer/AutomationController \
	/home/nick/UnrealEngine/Engine/Source/Developer/Localization/Public \
	/home/nick/UnrealEngine/Engine/Source/Developer/Localization/Public/Serialization \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Localization \
	/home/nick/UnrealEngine/Engine/Source/Developer/Localization \
	/home/nick/UnrealEngine/Engine/Source/Editor/AudioEditor/Classes \
	/home/nick/UnrealEngine/Engine/Source/Editor/AudioEditor/Public \
	/home/nick/UnrealEngine/Engine/Source/Editor/AudioEditor/Public/AssetTypeActions \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/AudioEditor \
	/home/nick/UnrealEngine/Engine/Source/Editor/AudioEditor \
	/home/nick/UnrealEngine/Engine/Source/Editor/LevelEditor/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/LevelEditor \
	/home/nick/UnrealEngine/Engine/Source/Editor/LevelEditor \
	/home/nick/UnrealEngine/Engine/Source/Developer/Settings/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Settings \
	/home/nick/UnrealEngine/Engine/Source/Developer/Settings \
	/home/nick/UnrealEngine/Engine/Source/Editor/IntroTutorials/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/IntroTutorials \
	/home/nick/UnrealEngine/Engine/Source/Editor/IntroTutorials \
	/home/nick/UnrealEngine/Engine/Source/Runtime/HeadMountedDisplay/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/HeadMountedDisplay \
	/home/nick/UnrealEngine/Engine/Source/Runtime/HeadMountedDisplay \
	/home/nick/UnrealEngine/Engine/Source/Editor/VREditor/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/VREditor \
	/home/nick/UnrealEngine/Engine/Source/Editor/VREditor \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Landscape/Classes \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Landscape/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Landscape \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Landscape \
	/home/nick/UnrealEngine/Engine/Source/Editor/PropertyEditor/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/PropertyEditor \
	/home/nick/UnrealEngine/Engine/Source/Editor/PropertyEditor \
	/home/nick/UnrealEngine/Engine/Source/Editor/ActorPickerMode/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/ActorPickerMode \
	/home/nick/UnrealEngine/Engine/Source/Editor/ActorPickerMode \
	/home/nick/UnrealEngine/Engine/Source/Editor/SceneDepthPickerMode/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/SceneDepthPickerMode \
	/home/nick/UnrealEngine/Engine/Source/Editor/SceneDepthPickerMode \
	/home/nick/UnrealEngine/Engine/Source/Editor/DetailCustomizations/Public \
	/home/nick/UnrealEngine/Engine/Source/Editor/DetailCustomizations/Public/Customizations \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/DetailCustomizations \
	/home/nick/UnrealEngine/Engine/Source/Editor/DetailCustomizations \
	/home/nick/UnrealEngine/Engine/Source/Editor/ClassViewer/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/ClassViewer \
	/home/nick/UnrealEngine/Engine/Source/Editor/ClassViewer \
	/home/nick/UnrealEngine/Engine/Source/Editor/GraphEditor/Public \
	/home/nick/UnrealEngine/Engine/Source/Editor/GraphEditor/Public/KismetNodes \
	/home/nick/UnrealEngine/Engine/Source/Editor/GraphEditor/Public/KismetPins \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/GraphEditor \
	/home/nick/UnrealEngine/Engine/Source/Editor/GraphEditor \
	/home/nick/UnrealEngine/Engine/Source/Editor/ContentBrowser/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/ContentBrowser \
	/home/nick/UnrealEngine/Engine/Source/Editor/ContentBrowser \
	/home/nick/UnrealEngine/Engine/Source/Runtime/NetworkFileSystem/Public \
	/home/nick/UnrealEngine/Engine/Source/Runtime/NetworkFileSystem/Public/Interfaces \
	/home/nick/UnrealEngine/Engine/Source/Runtime/CoreUObject/Public/Interfaces \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/NetworkFileSystem \
	/home/nick/UnrealEngine/Engine/Source/Runtime/NetworkFileSystem \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Sockets/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Sockets \
	/home/nick/UnrealEngine/Engine/Source/Runtime/Sockets \
	/home/nick/UnrealEngine/Engine/Source/Runtime/UMG/Public \
	/home/nick/UnrealEngine/Engine/Source/Runtime/UMG/Public/Animation \
	/home/nick/UnrealEngine/Engine/Source/Runtime/UMG/Public/Binding \
	/home/nick/UnrealEngine/Engine/Source/Runtime/UMG/Public/Blueprint \
	/home/nick/UnrealEngine/Engine/Source/Runtime/UMG/Public/Components \
	/home/nick/UnrealEngine/Engine/Source/Runtime/UMG/Public/Slate \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/UMG \
	/home/nick/UnrealEngine/Engine/Source/Runtime/UMG \
	/home/nick/UnrealEngine/Engine/Source/Runtime/MovieScene/Public \
	/home/nick/UnrealEngine/Engine/Source/Runtime/MovieScene/Public/Compilation \
	/home/nick/UnrealEngine/Engine/Source/Runtime/MovieScene/Public/Evaluation \
	/home/nick/UnrealEngine/Engine/Source/Runtime/MovieScene/Public/Evaluation/Blending \
	/home/nick/UnrealEngine/Engine/Source/Runtime/MovieScene/Public/Generators \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/MovieScene \
	/home/nick/UnrealEngine/Engine/Source/Runtime/MovieScene \
	/home/nick/UnrealEngine/Engine/Source/Runtime/MovieSceneTracks/Public \
	/home/nick/UnrealEngine/Engine/Source/Runtime/MovieSceneTracks/Public/Evaluation \
	/home/nick/UnrealEngine/Engine/Source/Runtime/MovieSceneTracks/Public/Sections \
	/home/nick/UnrealEngine/Engine/Source/Runtime/MovieSceneTracks/Public/Tracks \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/MovieSceneTracks \
	/home/nick/UnrealEngine/Engine/Source/Runtime/MovieSceneTracks \
	/home/nick/UnrealEngine/Engine/Source/Developer/CollectionManager/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/CollectionManager \
	/home/nick/UnrealEngine/Engine/Source/Developer/CollectionManager \
	/home/nick/UnrealEngine/Engine/Source/Editor/AddContentDialog/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/AddContentDialog \
	/home/nick/UnrealEngine/Engine/Source/Editor/AddContentDialog \
	/home/nick/UnrealEngine/Engine/Source/Developer/MeshUtilities/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/MeshUtilities \
	/home/nick/UnrealEngine/Engine/Source/Developer/MeshUtilities \
	/home/nick/UnrealEngine/Engine/Source/Developer/MeshMergeUtilities/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/MeshMergeUtilities \
	/home/nick/UnrealEngine/Engine/Source/Developer/MeshMergeUtilities \
	/home/nick/UnrealEngine/Engine/Source/Developer/HierarchicalLODUtilities/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/HierarchicalLODUtilities \
	/home/nick/UnrealEngine/Engine/Source/Developer/HierarchicalLODUtilities \
	/home/nick/UnrealEngine/Engine/Source/Developer/MeshReductionInterface/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/MeshReductionInterface \
	/home/nick/UnrealEngine/Engine/Source/Developer/MeshReductionInterface \
	/home/nick/UnrealEngine/Engine/Source/Developer/AssetTools/Public \
	/home/nick/UnrealEngine/Engine/Source/Developer/AssetTools/Public/AssetTypeActions \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/AssetTools \
	/home/nick/UnrealEngine/Engine/Source/Developer/AssetTools \
	/home/nick/UnrealEngine/Engine/Source/Editor/KismetCompiler/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/KismetCompiler \
	/home/nick/UnrealEngine/Engine/Source/Editor/KismetCompiler \
	/home/nick/UnrealEngine/Engine/Source/Editor/Kismet/Classes \
	/home/nick/UnrealEngine/Engine/Source/Editor/Kismet/Public \
	/home/nick/UnrealEngine/Engine/Source/Editor/Kismet/Public/Nodes \
	/home/nick/UnrealEngine/Engine/Source/Editor/Kismet/Public/WorkflowOrientedApp \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Kismet \
	/home/nick/UnrealEngine/Engine/Source/Editor/Kismet \
	/home/nick/UnrealEngine/Engine/Source/Runtime/ClothingSystemRuntimeInterface/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/ClothingSystemRuntimeInterface \
	/home/nick/UnrealEngine/Engine/Source/Runtime/ClothingSystemRuntimeInterface \
	/home/nick/UnrealEngine/Engine/Source/Runtime/NetworkReplayStreaming/NetworkReplayStreaming/Public \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/NetworkReplayStreaming \
	/home/nick/UnrealEngine/Engine/Source/Runtime/NetworkReplayStreaming/NetworkReplayStreaming \
	/home/nick/UnrealEngine/Engine/Source/Runtime/AudioMixer/Classes \
	/home/nick/UnrealEngine/Engine/Source/Runtime/AudioMixer/Public \
	/home/nick/UnrealEngine/Engine/Source/Runtime/AudioMixer/Public/Components \
	/home/nick/UnrealEngine/Engine/Source/Runtime/AudioMixer/Public/DSP \
	/home/nick/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/AudioMixer \
	/home/nick/UnrealEngine/Engine/Source/Runtime/AudioMixer \
	Source \
	Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/JSONQuery_UE4 \
	Source/JSONQuery_UE4 \
	/usr/include \

