# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/nick/UnrealEngine
GAMEPROJECTFILE =/home/nick/GitHub/JSONQuery_UE4/JSONQuery_UE4.uproject

TARGETS = \
	JSONQuery_UE4-Linux-Debug  \
	JSONQuery_UE4-Linux-DebugGame  \
	JSONQuery_UE4-Linux-Shipping  \
	JSONQuery_UE4-Linux-Test  \
	JSONQuery_UE4 \
	JSONQuery_UE4Editor-Linux-Debug  \
	JSONQuery_UE4Editor-Linux-DebugGame  \
	JSONQuery_UE4Editor-Linux-Shipping  \
	JSONQuery_UE4Editor-Linux-Test  \
	JSONQuery_UE4Editor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = mono "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool.exe"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping ShaderCompileWorker UnrealLightmass

StandardSet: RequiredTools UnrealFrontend UE4Editor

DebugSet: RequiredTools UnrealFrontend-Linux-Debug UE4Editor-Linux-Debug


JSONQuery_UE4-Linux-Debug:
	 $(PROJECTBUILD) JSONQuery_UE4 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

JSONQuery_UE4-Linux-DebugGame:
	 $(PROJECTBUILD) JSONQuery_UE4 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

JSONQuery_UE4-Linux-Shipping:
	 $(PROJECTBUILD) JSONQuery_UE4 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

JSONQuery_UE4-Linux-Test:
	 $(PROJECTBUILD) JSONQuery_UE4 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

JSONQuery_UE4:
	 $(PROJECTBUILD) JSONQuery_UE4 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

JSONQuery_UE4Editor-Linux-Debug:
	 $(PROJECTBUILD) JSONQuery_UE4Editor Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

JSONQuery_UE4Editor-Linux-DebugGame:
	 $(PROJECTBUILD) JSONQuery_UE4Editor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

JSONQuery_UE4Editor-Linux-Shipping:
	 $(PROJECTBUILD) JSONQuery_UE4Editor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

JSONQuery_UE4Editor-Linux-Test:
	 $(PROJECTBUILD) JSONQuery_UE4Editor Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

JSONQuery_UE4Editor:
	 $(PROJECTBUILD) JSONQuery_UE4Editor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /property:TargetFrameworkVersion=v4.5 /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
